// Code generated by reset tool; DO NOT EDIT.

package collector

import (
	"math/rand"
	"sync"
)


func (m *MetricsCollector) Reset() {
    if m == nil {
        return
    }
    
    // Поле: mu (sync.RWMutex)
    
    m.mu = sync.RWMutex{}
    
    
    // Поле: metrics (map[string]models.Metrics)
    
    clear(m.metrics)
    
    
    // Поле: pollCounter (int)
    
    m.pollCounter = 0
    
    
    // Поле: rand (*rand.Rand)
    
    if m.rand != nil {
        
        *m.rand = rand.Rand{}
        
    }
    
    
}
