// Code generated by reset tool; DO NOT EDIT.

package storage

import (
	"sync"
	"time"
)


func (m *MetricsStorage) Reset() {
    if m == nil {
        return
    }
    
    // Поле: metrics (map[string]models.Metrics)
    
    clear(m.metrics)
    
    
    // Поле: mu (*sync.Mutex)
    
    if m.mu != nil {
        
        *m.mu = sync.Mutex{}
        
    }
    
    
    // Поле: config (*MetricsStorageConfig)
    
    if m.config != nil {
        
        if resetter, ok := interface{}(m.config).(interface{ Reset() }); ok {
            resetter.Reset()
        } else {
            *m.config = MetricsStorageConfig{}
        }
        
    }
    
    
    // Поле: saveTicker (*time.Ticker)
    
    if m.saveTicker != nil {
        
        *m.saveTicker = time.Ticker{}
        
    }
    
    
    // Поле: done (chan bool)
    
    m.done = nil
    
    
}
