// Code generated by reset tool; DO NOT EDIT.

package metricssender

import (
	"sync"

	retriableagent "github.com/Ko4etov/go-metrics/internal/service/retriable_agent"
	"github.com/go-resty/resty/v2"
)


func (m *MetricsSenderService) Reset() {
    if m == nil {
        return
    }
    
    // Поле: ServerAddress (string)
    
    m.ServerAddress = ""
    
    
    // Поле: HashKey (string)
    
    m.HashKey = ""
    
    
    // Поле: Client (*resty.Client)
    
    if m.Client != nil {
        
        *m.Client = resty.Client{}
        
    }
    
    
    // Поле: BatchSize (int)
    
    m.BatchSize = 0
    
    
    // Поле: RateLimit (int)
    
    m.RateLimit = 0
    
    
    // Поле: RetiebleAgent (*retriableagent.RetriableAgent)
    
    if m.RetiebleAgent != nil {
        
        *m.RetiebleAgent = retriableagent.RetriableAgent{}
        
    }
    
    
    // Поле: jobs (chan []models.Metrics)
    
    m.jobs = nil
    
    
    // Поле: wg (sync.WaitGroup)
    
    m.wg = sync.WaitGroup{}
    
    
}
